name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/declarative-mocks

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Build distribution
        run: poetry build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
